fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: 'venv|env|alembic/versions/'
      - id: trailing-whitespace
        exclude: 'venv|env|alembic/versions/'
  # We keep black even if ruff checks for formatting because ruff doesn't auto fix those issues
  # and black does
  # Ruff docs: "As a project, Ruff is designed to be used alongside Black..."
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.290
    hooks:
      - id: ruff
        args:
          - --fix # automatically fixes what can be autofixed
