repos:
- repo: local
  hooks:
  - id: isort
    name: "ISort"
    language: system
    entry: isort
    types: [file, python]
- repo: local
  hooks:
  - id: black
    name: "Black"
    language: system
    entry: black
    types: [file, python]
- repo: local
  hooks:
  - id: pylint
    name: "pylint"
    entry: pylint
    language: system
    types: [python]
    args:
    - "-rn"
