[tool.black]
line-length = 120
target-version = ['py310']
force-exclude = 'env|venv|alembic/versions/'

[tool.ruff]
line-length = 120
# E501 (line-length) -> check by black already
ignore = ["E501"]
extend-select = ["I001"]
target-version = "py310"
extend-exclude = ["env", "*/versions/"]
